### ISSUE TITLE
Comparison with NFFT3 C library

### ISSUE THREAD

**Issue by berceanu** [JuliaMath/NFFT.jl#38]
How does this compare to https://github.com/NFFT/nfft/tree/develop/julia?

**Comment by JeffFessler** [comment]
For starters, this one is pure Julia so it is easy to install and use: no C compilation needed.
(If both were pure Julia then it would be easy to compare their speed and accuracy.)

**Comment by tknopp** [comment]
Ah interesting. Have not seen that. @berceanu could you specify more concretely what you would like to compare? Speed? Functionality?

I did some benchmarking in the early days of NFFT.jl and was in the same range as the C library (which I partly co-authored). Maybe a factor of 1.2 slower. But since then Julia evolved a lot and thus I am not fully sure where we are. Thus, I think it would be good if we would have some sort of benchmark, not only against the C library but also against the recent GPU efforts.

Here is a publication that benchmarked NFFT.jl against an alternative approach (https://epubs.siam.org/doi/pdf/10.1137/17M1134822)

Finally: Actually, the most important question is how to implement the convolution (-like) matrix. I started with a look-up table approach, but now there is the option to precompute the entire sparse matrix. I use this in an MRI (Compressed Sensing + Parallel Imaging + Field Inhomogeneity) case, where the NFFT is applied thousands of times. In that case the sparse matrix approach is the fastest what I have seen.

**Comment by berceanu** [comment]
Do the GPU efforts have a Julia implementation?

**Comment by tknopp** [comment]
No but we might integrate this into NFFT.jl, if someone is interested working on that.

I am aware of
https://github.com/andyschwarzl/gpuNUFFT
which is written in C++

**Comment by kellertuer** [comment]
There seems to be a package working on the NFFT in Julia now, too, see https://github.com/NFFT/NFFT3.

**Comment by tknopp** [comment]
Yes, this could be interesting for a performance comparison. But do you recommend using that? NFFT3 has certainly still some more features right now but from a Julia perspective I would encourage that we try unifying forces and work together on a single, full-featured pure Julia NFFT package. This Julia package is so much more simple than NFFT3, to which (if that is not clear) I made quite some contributions.

**Comment by kellertuer** [comment]
Oh, I never used the NFFT actually, my main connection might be that (a) I shared an office with Jens once during my PhD and was just on the other floor in Chemnitz for a while until I moved recently. So I just noticed this. I think the idea is to reimplement NFFT3 in Julia in that project, so I hope that joined forces might be a good idea. What do you think @mischmi96 ?
Namewise, maybe the name without a number is nicer.

**Comment by mischmi96** [comment]
Well, I think there are two different goals here. The (current) view in our working group is that we still keep one version of the NFFT library (and that includes NFCT, NFST, NFSFT, fastsum, ...) in C and only provide interfaces for different languages. We can't just discontinue the Matlab interface since a large number of people (including Ralf Hielscher with MTEX) use the library with Matlab. We do not have the resources to maintain separate implementations of every algorithm in Matlab, Julia and (in the future) Python. In the end, this decision lies with @DanielPotts (Maybe one of the other developers wants to give their opinion? @tvolkmer @michaelquellmalz @ralfHielscher @felixbartel )

From a practical standpoint: I work with the Julia packages almost every day. They are also required for our packages that we use in current research.

**Comment by kellertuer** [comment]
Oh, I never intended to discontinue a different language (C/C++/Matlab), just whether it is maybe better to have one package in Julia instead of two. It might still be that one can then choose a backend, when both a Julia and a C/C++ implementation are available and all that are only available in C are interfaced.

**Comment by tknopp** [comment]
yes exactly. Having joint interfaces makes it easy to switch backends just like it is done with `AbstractFFT` which can use both `FFTW` or `CUDA`. I am not sure if the user base for NFFT libraries is so large that we should work on common interfaces. As the project maintainer of NFFT.jl I would actually be more interested to find out what people are missing from NFFT.jl and how it can be improve. 

But anyway, I think Ronny just wanted to a link to the package which I totally appreciate. It would be awesome if we could make a performance comparison. Would be quite interesting if NFFT.jl is faster on dimensions larger than 3 since we generate dedicated code for arbitrary dimensions.

**Comment by kellertuer** [comment]
Sure, I did not mean to abandon anything; compare and if possible look for a common abtract basis, so that users can easily enjoy the advantages of both packages (i.e. switch between using one or the other as a backend).

**Comment by tknopp** [comment]
I started working on some benchmarks here: https://github.com/tknopp/NFFT.jl/blob/master/test/performance.jl#L87  still completely WIP. This will require https://github.com/NFFT/NFFT3.jl/issues/12 to be solved.

**Comment by tknopp** [comment]
Here is a first comparison of the accuracy for a 2D NFFT ([this code](https://github.com/tknopp/NFFT.jl/blob/master/test/comparison.jl#L6) generates the plot): 

![accuracy_D2](https://user-images.githubusercontent.com/3109172/147793578-6ae263ee-25e6-46c2-99de-0a302487576d.png)

I would say this looks quite good for two different libraries implementing the same algorithm. In a first step I was only capable getting the same result in 1D. But then I realized that there might be some difference because of row-major vs column major in 2D ....   
The solution was a [permutdims](https://github.com/tknopp/NFFT.jl/blob/master/test/comparison.jl#L47). I am not sure if this is a bug in the NFFT3.jl wrapper (or NFFT.jl?) or if the user should just know that. @mischmi96: Are you aware of that?

**Comment by tknopp** [comment]
closing this, since we have now both performance and accuracy comparisons.
